apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-vm2
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: vbs-vm-class
  imageName: cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.ova
  powerState: poweredOff
  vmMetadata:
    configMapName: user-data-2
    transport: ExtraConfig
  networkInterfaces:
    - networkName: "VM Network"
      ethernetCardType: "vmxnet3"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-2
    namespace: default
data:
  guestinfo.userdata: I2Nsb3VkLWNvbmZpZwpncm91cHM6CiAgLSBhZG1pbmdyb3VwOiBbcm9vdCxzeXNdCiAgLSBjbG91ZC11c2VycwoKc3lzdGVtX2luZm86CiAgZGVmYXVsdF91c2VyOgogICAgbmFtZTogdWJ1bnR1CiAgICBwbGFpbl90ZXh0X3Bhc3N3ZDogJ2NhJGhjMHcnCiAgICBob21lOiAvaG9tZS91YnVudHUKICAgIHNoZWxsOiAvYmluL2Jhc2gKICAgIGxvY2tfcGFzc3dkOiBmYWxzZQogICAgZ2Vjb3M6IFVidW50dQogICAgZ3JvdXBzOiBbYWRtLCBhdWRpbywgY2Ryb20sIGRpYWxvdXQsIGZsb3BweSwgdmlkZW8sIHBsdWdkZXYsIGRpcCwgbmV0ZGV2XQoKdXNlcnM6CiAgLSBkZWZhdWx0CiAgLSBuYW1lOiBmb29iYXIKICAgIGdlY29zOiBGb28gQi4gQmFyCiAgICBwcmltYXJ5X2dyb3VwOiBmb29iYXIKICAgIGdyb3VwczogY2xvdWQtdXNlcnMKICAgIGV4cGlyZWRhdGU6ICcyMDMyLTA5LTAxJwogICAgbG9ja19wYXNzd2Q6IGZhbHNlCiAgICBob21lOiAvaG9tZS9mb29iYXIKICAgIHNoZWxsOiAvYmluL2Jhc2gKICAgIHBhc3N3ZDogJDYkZ1JzRFpYaWxqSi9Ma3dnJEJtUDRESVJxaHZkTmJpR1NKQktZemYuSVNLWmFUTFd6amt0SGVtcnVzaWN5Ny81L0w5ZVFKNzNCcXpNMVVWNkJ4Vk9ucXYudTJXRWRjNW9FSnouVjcx
  guestinfo.userdata.encoding: base64
