apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: vbs-vm-class
spec:
  configSpec:
    _typeName: VirtualMachineConfigSpec
    latencySensitivity:
      _typeName: LatencySensitivity 
      level: low
    flags:
      _typeName: VirtualMachineFlagInfo
    #  vbsEnabled: true
      virtualMmuUsage: "on"
    #  vvtdEnabled: true
    #nestedHVEnabled: true
    #bootOptions:
    #  _typeName: VirtualMachineBootOptions
    #  efiSecureBootEnabled: true  # required vm hardware version for secure boot >= vmx-13
  policies:
      resources:
        requests:
          memory: 4Gi   # The memory reservation must be equal to the VM memory for latency sensitivity.
          cpu: 3
  hardware:
    cpus: 3
    memory: 4Gi
    #devices:
    #  dynamicDirectPathIODevices:
    #  - vendorID: 0x14e4
    #    deviceID: 0x165f
