apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: welcome-message
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
          "system": {
            "welcome_message":
{                 "message": "\{align:center}

\n\n\n\n VMware Edge Cloud Orchestrator - Edge Host{/color}
{/align}\n\n\n\n\n\n\n\n\n{align:center}No Unauthorized Access{/color}{/align}

\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n{align:center} For access contact Alan Renouf on 555 555-5555{/color}
{/align}

"
            }
          }
      }
    }
